import Header from '@/common/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/common/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='w-screen h-[56px] border-[1px] border-black'>
          <Header />
        </header>
        <div className='flex w-full h-[calc(100vh-56px)]'>
          <div className='top-0 h-60 z-10 bg-white fixed'>
            <Navbar />
          </div>
          <div className={`${inter.className} ml-[248px] flex-1 border-[1px] border-black`}>{children}</div>
        </div>
      </body>
    </html>
  )
}
